version: '3'
services: 
  redis-server:
    image: 'redis'
  node-app:
    build: .
    ports:
      - "4001:8081"

# This is a Docker Compose file that defines a multi-container application.
# docker run myimage -> docker-compose up
# docker build . and docker run myimage -> docker-compose up --build
# docker-compose up -d -> run in detached mode
# docker-compose down -> stop all containers

