version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '7026:5173'
        volumes:
            - /mw/react/node_modules
            - .:/mw/react
